#
# repository of processed observations
archiveDir: /var/mellow/mastodon/archive
#
# repository of converted observations
cookedDir: /var/mellow/mastodon/cooked
#
# repository of problem files
failureDir: /var/mellow/mastodon/failure
#
# repository of freshly collected observations
freshDir: /var/mellow/mastodon/fresh
#
#
rawDir: /var/mellow/mastodon/raw
#
# test artifacts
testDir: /var/mellow/mastodon/test
#
# database connection
dbConn: "postgresql+psycopg2://mastodon_client:batabat@localhost:5432/mastodon"
#
# true, echo SQL statements
#sqlEchoEnable: true
sqlEchoEnable: false
#
