--
-- Title: observation.psql
-- Description: 
--
create table mastodon_observation (
  id            bigserial  primary key,
  baseline_dbm  real       not null,
  freq_hz       int        not null,
  load_log_id   bigint     not null,
  constraint load_lg_id foreign key(load_log_id) references mastodon_load_log(id),
  power_dbm     real       not null
);

grant select, insert, update, delete on mastodon_observation to mastodon_client;
grant usage, select on sequence mastodon_observation_id_seq to mastodon_client;

create unique index obs_freq_load_log on mastodon_observation(freq_hz, load_log_id);
